language: ruby
rvm:
- 2.4.0
deploy:
  provider: rubygems
  api_key:
    secure: ph/5I0x4nQebMsUUUJelts/S69KFLJxgPqDltsfrgATVesukd4XjCZXzCHq+1xtViKqzhOHm4LC1AaQlNjGpiJGe0/VeTnI/Xdp+YQsR8JiIE/FZ93CZ8qHJI6R5CgMqNi1rBgUi2qjZNoXOM3g0YJ0mTGVO6UlxhXrs+nU6Vf9vYypUMilHWuioWUVji2pvF3KK4yKssfpZ+jd+1z0d7Ei2sUE0CuOINcZ60HVK9dMvMVd2I98sPQZrnZYZ77R0Lp8pmTJ+bByZdcG28v1zCdf6m9pank4ABF2m8rDkbyieKJ280CgCv756pNzebQEu1ZiycitFO/n881PbHFRZRevvH6txFN3oc4Whg4VQkwI/O4NL2XmjgbiQPEldU3PFK6y7Vm/zbSdPEFBGkb7G5oyaDcxIeqxZzHXBPvVKHUX/GNMTGVli6PIt+tfX2HaGtC+k0NbxZP7g7+C1380d20rNKnokMiGZP+GgdBttHnnCdgXu7GjR2l/xNL7R48squ+LlH05haOaKJcybAGxOwEzRke6BQxsF0iHEg5/EYbpP5F7LEmxcOdep6n1c6X7yJHaAP8TTsivTMlBJKr3Oo9yXrBkAdZWRCpfWMkQabSxI+m6K/KU98ynm6Je8NYqmH0jLR4Wn6lZFyeBZlSBmXKpUlerdA34F09+OGE0sziY=
  ruby: 2.4.0
  gem: tiny_client
  gemspec: tiny_client.gemspec
  on:
    tags: true
